#!/usr/bin/sh

src='/data/mdi0316/WORK'
dest='/storage/mdi0316/AC2T'
mkdir -p $dest/CSV
mkdir -p $dest/CSV/CHARGES
mkdir -p $dest/CSV/CHARGES/GAMESS
mkdir -p $dest/CSV/CHARGES/NWCHEM
mkdir -p $dest/CSV/ENERGIES
mkdir -p $dest/CSV/ENERGIES/GAMESS
mkdir -p $dest/CSV/ENERGIES/NWCHEM
mkdir -p $dest/TAR

if [ $# -eq 0 ]; then
   rsync_csv=1
   rsync_mono=1
   rsync_dime=1
   rsync_charges=1
   tar_all=0
else
   rsync_csv=$1
   rsync_mono=$2
   rsync_dime=$3
   rsync_charges=$4
   tar_all=$5
fi

find_all_files()
{
  echo "find $1 -mindepth $2 -maxdepth $2 -name 'log*' -o -name 'gms*inp' -o -name 'gms*dat' -o -name 'gms*wfn' | grep $3 >> $4 "
  find $1 -mindepth $2 -maxdepth $2 -name 'log*' -o -name 'gms*inp' -o -name 'gms*dat' -o -name 'gms*wfn' | grep $3 >> /storage/mdi0316/$4
}

rsync_from_file()
{
echo reading $1
echo $1 is `wc -l $1` lines long
for file_abs_path in `cat $1`; do 
  dest_dir=` echo $file_abs_path | sed 's/data/storage/g; s/WORK/AC2T/g' | sed 's/\// /g' | awk '{$NF="";print $0}' | sed 's/ /\//g; s/storage/\/storage/g'`
  mkdir -p $dest_dir
  echo "rsync -ra --update $file_abs_path $dest_dir"
  rsync -ra --update $file_abs_path $dest_dir
  done
}

## CSV 
if [ $rsync_csv = 1 ]; then
  dest_dir="/storage/mdi0316/AC2T/CSV/MONOMERS/"
  mkdir -p $dest_dir
  for file_name in `ls /data/mdi0316/WORK/MONOMERS/CSV/`; do
    echo $file_name
    rsync -ra --update /data/mdi0316/WORK/MONOMERS/CSV/$file_name $dest_dir
    done
  
  for file_name in scan_opt.csv scan_err.csv scan_dft_ene.csv scan_dft_eda.csv; do
    for ii in `find /data/mdi0316/WORK/DIMERS/*/CSV -name $file_name` ; do
        dest_dir=`echo $ii | sed "s/\// /g" | awk '{print "/storage/mdi0316/AC2T/CSV/DIMERS/"$5}'`
        dest_file=`echo $ii | sed "s/\// /g" | awk '{print "/storage/mdi0316/AC2T/CSV/DIMERS/"$5"/"$7"_"$8"_"$9}'`
        mkdir -p $dest_dir
        echo "rsync -rva --update $ii $dest_file"
        rsync -ra --update $ii $dest_file
      done
    done
  
  for file_name in scan_mp2_ene.csv scan_mp2_eda.csv; do
    for ii in `find /data/mdi0316/WORK/DIMERS/*/CSV -name $file_name` ; do
        dest_dir=`echo $ii | sed "s/\// /g" | awk '{print "/storage/mdi0316/AC2T/CSV/DIMERS/"$5}'`
        dest_file=`echo $ii | sed "s/\// /g" | awk '{print "/storage/mdi0316/AC2T/CSV/DIMERS/"$5"/"$7"_"$8}'`
        mkdir -p $dest_dir
        echo "rsync -ra --update $ii $dest_file"
        rsync -ra --update $ii $dest_file
      done
    done
fi
## CSV 

## MONOMERS inp/log files
if [ $rsync_mono = 1 ]; then
  if [ -f "all_gamess_mono_data" ]; then
    echo all_gamess_mono_data exists
    else
    echo printing all_gamess_mono_data
    find_all_files $src/MONOMERS 7 'OPT/DFT'   all_gamess_mono_data 
    find_all_files $src/MONOMERS 7 'ENE/DFT'   all_gamess_mono_data 
    find_all_files $src/MONOMERS 7 'ENE/MP2'   all_gamess_mono_data 
    find_all_files $src/MONOMERS 7 'ENE/CCSDT' all_gamess_mono_data 
    fi
  rsync_from_file /storage/mdi0316/all_gamess_mono_data 
  fi

## DIMERS inp/log files
if [ $rsync_dime = 1 ]; then
  if [ -f "all_gamess_dime_data" ]; then
    echo all_gamess_dime_data exists
    else
    echo printing all_gamess_dime_data
    find_all_files $src/DIMERS 11 'OPT/DFT'                          all_gamess_dime_data 
    find_all_files $src/DIMERS 12 'ENE/OPT_from_DFT_N311_B3LYP/DFT'  all_gamess_dime_data
    find_all_files $src/DIMERS 11 'ENE/OPT_from_DFT_N311_B3LYP/MP2'  all_gamess_dime_data
    fi
  rsync_from_file /storage/mdi0316/all_gamess_dime_data 
  fi

## CHARGES begins ##
if [ $rsync_charges = 1 ]; then
  #GAMESS
  if [ -f "all_gamess_charges" ]; then
    echo all_gamess_charges exists
    else
    echo printing all_gamess_charges
    echo "find ${src}/DIMERS -name 'atomic_charges.csv' | grep "T_90\/P_90" > all_gamess_charges"
    find ${src}/DIMERS -name 'atomic_charges.csv' | grep "T_90\/P_90" > /storage/mdi0316/all_gamess_charges
    fi
  echo reading all_gamess_charges
  echo all_gamess_charges is `wc -l all_gamess_charges` lines long
  for ii in `cat /storage/mdi0316/all_gamess_charges`; do
      new_ii=`echo $ii | sed 's/\// /g'| awk '{print $5" "$10" "$11" "$12" "$13" "$14" "$15" "$16}' | sed 's/.csv /.csv/g; s/ /_/g'`
      new_charge_file=$dest/CSV/CHARGES/GAMESS/$new_ii
      rsync -ra --update $ii $new_charge_file
      done
  #NWCHEM
  if [ -f "all_nwchem_charges" ]; then
    echo all_nwchem_charges exists
    else
    echo printing all_nwchem_charges
    echo "find ${src}/NWCHEM/DIMERS -name 'atomic_charges.csv' | grep "T_90\/P_90" > all_nwchem_charges"
    find ${src}/NWCHEM/DIMERS -name 'atomic_charges.csv' | grep "T_90\/P_90" > /storage/mdi0316/all_nwchem_charges
    fi
  echo reading all_nwchem_charges
  echo all_nwchem_charges is `wc -l all_nwchem_charges` lines long
  for ii in `cat /storage/mdi0316/all_nwchem_charges`; do
      new_ii=`echo $ii | sed 's/\// /g' | awk '{print $6" "$8" "$9" "$10" "$11" "$12" "$13" "$14}' | sed 's/.csv /.csv/g; s/ /_/g'`
      new_charge_file=$dest/CSV/CHARGES/NWCHEM/$new_ii
      rsync -ra --update $ii $new_charge_file
      done
fi
## CHARGES ends  ##

## TAR ALL
if [ $tar_all = 1 ]; then 
  echo 'Tarring all dirs'
  if [ -f "all_dft_P_dirs" ]; then
    echo all_dft_P_dirs exists
    else
    echo printing all_dft_P_dirs
    find AC2T -name "P_*" | grep ENE | grep -v MP2 > /storage/mdi0316/all_dft_P_dirs
    find AC2T -name "P_*" | grep ENE | grep    MP2 > /storage/mdi0316/all_mp2_P_dirs
  fi
  for P_dir in `cat /storage/mdi0316/all_dft_P_dirs`; do
    dest_name=`echo $P_dir | sed "s/\// /g" | awk '{print $3"_"$9"_"$10"_"$11"_"$12}'`
    dest_obj=$dest/TAR/${dest_name}.tar.gz
    tar -zcvf $dest_obj $P_dir 
    done
  fi
## TAR ALL


## MOFs 
rsync -ravz --update /data/mdi0316/WORK/MOFS/ /storage/mdi0316/MOFS
## MOFs 
